version: '3'
services:
  jenkins:
    build: .
    container_name: jenkins-dummy
    ports:
      - '7777:8080'
      - '50000:50000'
    volumes:
      - 'jenkins_dummy:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  jenkins_dummy: